### ISSUE TITLE
FR: Use multiple SDR devices?

### ISSUE THREAD

**Issue by tubalainen** [sdr-enthusiasts/docker-shipfeeder#44]
I am currently running ais-catcher in docker with three SDRs. Is it possible to use multiple SDR devices with this docker setup?

Thanks :)

**Comment by kx1t** [comment]
yes it is. However, I am wondering what you are using those 3 SDRs for? Most I've seen configured is 2 -- 1 SDR for channels AB and 1 SDR for channels CD

Note that you can add a whole custom configuration to the `ais-catcher` component of shipfeeder with the `AISCATCHER_EXTRA_OPTIONS` env variable. See the Readme for more info.
